### ISSUE TITLE
Release 1.0.6 with node 21

### ISSUE THREAD

**Issue by krsyoung** [harled/docker-puppeteer#6]
Release a new version of the puppeteer image based on:

- node:21-slim

**Comment by jonathanloos** [comment]
@krsyoung curious if this was completed? I can see that [1.0.6](https://hub.docker.com/layers/krsyoung/puppeteer/1.0.6/images/sha256-b945e8d488305164024b4b0163156be9727e2c14aa699bd409e51716fbfaf26e?context=explore) is available but don't see an update here.

Also can try to help if you need!

**Comment by krsyoung** [comment]
@jonathanloos, I just pushed the PR for it (yes, it was pushed to Docker Hub via the 1.0.6 tag). 

It was focused on resolving the node seg fault problem which seems to continue to be more related to Mac OS / virtualization vs anything actually npm/node related (re: https://github.com/docker/for-mac/issues/6824)

**Comment by jonathanloos** [comment]
Ack, thank you for the update! We'll pull and test the latest image.
